// Copyright (c) 2019-2022 Iotic Labs Ltd. All rights reserved.

// Iotics Web protocol definitions (input)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: iotics/api/input.proto

package ioticsapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representation of an input.
type InputID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Input Identifier string representation (simple string) (unique within the scope of a twin identifier's input set)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Twin identifier string representation (simple string) (twin to which the feed belongs)
	TwinId string `protobuf:"bytes,2,opt,name=twinId,proto3" json:"twinId,omitempty"`
	// Host identifier string representation (simple string) (Host to which the twin belongs)
	HostId string `protobuf:"bytes,3,opt,name=hostId,proto3" json:"hostId,omitempty"`
}

func (x *InputID) Reset() {
	*x = InputID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputID) ProtoMessage() {}

func (x *InputID) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputID.ProtoReflect.Descriptor instead.
func (*InputID) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{0}
}

func (x *InputID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InputID) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *InputID) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

// DeleteInputRequest is used to delete an input from a given twin.
type DeleteInputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DeleteInputRequest headers
	Headers *Headers `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// DeleteInputRequest mandatory arguments
	Args *DeleteInputRequest_Arguments `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *DeleteInputRequest) Reset() {
	*x = DeleteInputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInputRequest) ProtoMessage() {}

func (x *DeleteInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInputRequest.ProtoReflect.Descriptor instead.
func (*DeleteInputRequest) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteInputRequest) GetHeaders() *Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DeleteInputRequest) GetArgs() *DeleteInputRequest_Arguments {
	if x != nil {
		return x.Args
	}
	return nil
}

// DeleteInputResponse describes a deleted input.
type DeleteInputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DeleteInputResponse headers
	Headers *Headers `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// DeleteInputResponse payload
	Payload *DeleteInputResponse_Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DeleteInputResponse) Reset() {
	*x = DeleteInputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInputResponse) ProtoMessage() {}

func (x *DeleteInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInputResponse.ProtoReflect.Descriptor instead.
func (*DeleteInputResponse) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteInputResponse) GetHeaders() *Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DeleteInputResponse) GetPayload() *DeleteInputResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// DescribeInputRequest is used to request the input metadata.
type DescribeInputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DescribeInputRequest headers
	Headers *Headers `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// DescribeInputRequest mandatory arguments
	Args *DescribeInputRequest_Arguments `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *DescribeInputRequest) Reset() {
	*x = DescribeInputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeInputRequest) ProtoMessage() {}

func (x *DescribeInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeInputRequest.ProtoReflect.Descriptor instead.
func (*DescribeInputRequest) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeInputRequest) GetHeaders() *Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DescribeInputRequest) GetArgs() *DescribeInputRequest_Arguments {
	if x != nil {
		return x.Args
	}
	return nil
}

// DescribeInputResponse provides metadata lookup for individual input resources.
type DescribeInputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DescribeInputResponse headers
	Headers *Headers `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// DescribeInputResponse payload
	Payload *DescribeInputResponse_Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DescribeInputResponse) Reset() {
	*x = DescribeInputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeInputResponse) ProtoMessage() {}

func (x *DescribeInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeInputResponse.ProtoReflect.Descriptor instead.
func (*DescribeInputResponse) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeInputResponse) GetHeaders() *Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DescribeInputResponse) GetPayload() *DescribeInputResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// UpsertInputWithMeta is used to describe the full input state. Used in UpsertTwinRequest.
type UpsertInputWithMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Input Identifier string representation (simple string) (unique within the scope of a twin identifier's input set)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Values to set
	Values []*Value `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	// Properties to set
	Properties []*Property `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
}

func (x *UpsertInputWithMeta) Reset() {
	*x = UpsertInputWithMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertInputWithMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertInputWithMeta) ProtoMessage() {}

func (x *UpsertInputWithMeta) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertInputWithMeta.ProtoReflect.Descriptor instead.
func (*UpsertInputWithMeta) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertInputWithMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertInputWithMeta) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *UpsertInputWithMeta) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

// InputMessage describe a message that can be sent to an input
type InputMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// OccurredAt is the UTC timestamp of the message.
	// Typically this is either the time at which an application sent this message
	// or the time applicable to the message itself. (Optional: set to host time if not provided)
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=occurredAt,proto3" json:"occurredAt,omitempty"`
	// Mime is the mime type of the encoded data.
	Mime string `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	// Data is the actual message, encoded according the the mime type. The data should follow the Input's
	// value definitions but that is not enforced. (See also Value)
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InputMessage) Reset() {
	*x = InputMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessage) ProtoMessage() {}

func (x *InputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessage.ProtoReflect.Descriptor instead.
func (*InputMessage) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{6}
}

func (x *InputMessage) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *InputMessage) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *InputMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ReceiveInputMessageRequest is used to receive messages sent to a given Input.
type ReceiveInputMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ReceiveInputMessageRequest headers
	Headers *Headers `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// ReceiveInputMessageRequest mandatory arguments
	Args *ReceiveInputMessageRequest_Arguments `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *ReceiveInputMessageRequest) Reset() {
	*x = ReceiveInputMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveInputMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveInputMessageRequest) ProtoMessage() {}

func (x *ReceiveInputMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveInputMessageRequest.ProtoReflect.Descriptor instead.
func (*ReceiveInputMessageRequest) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiveInputMessageRequest) GetHeaders() *Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ReceiveInputMessageRequest) GetArgs() *ReceiveInputMessageRequest_Arguments {
	if x != nil {
		return x.Args
	}
	return nil
}

// ReceiveInputMessageResponse contains a message sent to the Input.
type ReceiveInputMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ReceiveInputMessageResponse headers
	Headers *Headers `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// ReceiveInputMessageResponse payload
	Payload *ReceiveInputMessageResponse_Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ReceiveInputMessageResponse) Reset() {
	*x = ReceiveInputMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveInputMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveInputMessageResponse) ProtoMessage() {}

func (x *ReceiveInputMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveInputMessageResponse.ProtoReflect.Descriptor instead.
func (*ReceiveInputMessageResponse) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{8}
}

func (x *ReceiveInputMessageResponse) GetHeaders() *Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ReceiveInputMessageResponse) GetPayload() *ReceiveInputMessageResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// DeleteInputRequest arguments.
type DeleteInputRequest_Arguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Input to delete
	InputId *InputID `protobuf:"bytes,1,opt,name=inputId,proto3" json:"inputId,omitempty"`
}

func (x *DeleteInputRequest_Arguments) Reset() {
	*x = DeleteInputRequest_Arguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInputRequest_Arguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInputRequest_Arguments) ProtoMessage() {}

func (x *DeleteInputRequest_Arguments) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInputRequest_Arguments.ProtoReflect.Descriptor instead.
func (*DeleteInputRequest_Arguments) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DeleteInputRequest_Arguments) GetInputId() *InputID {
	if x != nil {
		return x.InputId
	}
	return nil
}

// DeleteInputResponse payload.
type DeleteInputResponse_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deleted input
	InputId *InputID `protobuf:"bytes,1,opt,name=inputId,proto3" json:"inputId,omitempty"`
}

func (x *DeleteInputResponse_Payload) Reset() {
	*x = DeleteInputResponse_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInputResponse_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInputResponse_Payload) ProtoMessage() {}

func (x *DeleteInputResponse_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInputResponse_Payload.ProtoReflect.Descriptor instead.
func (*DeleteInputResponse_Payload) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DeleteInputResponse_Payload) GetInputId() *InputID {
	if x != nil {
		return x.InputId
	}
	return nil
}

// DescribeInputRequest arguments.
type DescribeInputRequest_Arguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Input to describe
	InputId *InputID `protobuf:"bytes,1,opt,name=inputId,proto3" json:"inputId,omitempty"`
}

func (x *DescribeInputRequest_Arguments) Reset() {
	*x = DescribeInputRequest_Arguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeInputRequest_Arguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeInputRequest_Arguments) ProtoMessage() {}

func (x *DescribeInputRequest_Arguments) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeInputRequest_Arguments.ProtoReflect.Descriptor instead.
func (*DescribeInputRequest_Arguments) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DescribeInputRequest_Arguments) GetInputId() *InputID {
	if x != nil {
		return x.InputId
	}
	return nil
}

// DescribeInputResponse metadata result.
type DescribeInputResponse_MetaResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Values semantically describing the Input messages
	Values []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	// Custom properties associated with this input.
	Properties []*Property `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
}

func (x *DescribeInputResponse_MetaResult) Reset() {
	*x = DescribeInputResponse_MetaResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeInputResponse_MetaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeInputResponse_MetaResult) ProtoMessage() {}

func (x *DescribeInputResponse_MetaResult) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeInputResponse_MetaResult.ProtoReflect.Descriptor instead.
func (*DescribeInputResponse_MetaResult) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DescribeInputResponse_MetaResult) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DescribeInputResponse_MetaResult) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

// DescribeInputResponse payload.
type DescribeInputResponse_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Described input
	InputId *InputID `protobuf:"bytes,1,opt,name=inputId,proto3" json:"inputId,omitempty"`
	// Metadata result
	Result *DescribeInputResponse_MetaResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DescribeInputResponse_Payload) Reset() {
	*x = DescribeInputResponse_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeInputResponse_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeInputResponse_Payload) ProtoMessage() {}

func (x *DescribeInputResponse_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeInputResponse_Payload.ProtoReflect.Descriptor instead.
func (*DescribeInputResponse_Payload) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{4, 1}
}

func (x *DescribeInputResponse_Payload) GetInputId() *InputID {
	if x != nil {
		return x.InputId
	}
	return nil
}

func (x *DescribeInputResponse_Payload) GetResult() *DescribeInputResponse_MetaResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// ReceiveInputMessageRequest arguments.
type ReceiveInputMessageRequest_Arguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Input to listen messages from
	InputId *InputID `protobuf:"bytes,1,opt,name=inputId,proto3" json:"inputId,omitempty"`
}

func (x *ReceiveInputMessageRequest_Arguments) Reset() {
	*x = ReceiveInputMessageRequest_Arguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveInputMessageRequest_Arguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveInputMessageRequest_Arguments) ProtoMessage() {}

func (x *ReceiveInputMessageRequest_Arguments) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveInputMessageRequest_Arguments.ProtoReflect.Descriptor instead.
func (*ReceiveInputMessageRequest_Arguments) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ReceiveInputMessageRequest_Arguments) GetInputId() *InputID {
	if x != nil {
		return x.InputId
	}
	return nil
}

type ReceiveInputMessageResponse_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Input the message has been sent to
	InputId *InputID `protobuf:"bytes,1,opt,name=inputId,proto3" json:"inputId,omitempty"`
	// Input message
	Message *InputMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReceiveInputMessageResponse_Payload) Reset() {
	*x = ReceiveInputMessageResponse_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iotics_api_input_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveInputMessageResponse_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveInputMessageResponse_Payload) ProtoMessage() {}

func (x *ReceiveInputMessageResponse_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_iotics_api_input_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveInputMessageResponse_Payload.ProtoReflect.Descriptor instead.
func (*ReceiveInputMessageResponse_Payload) Descriptor() ([]byte, []int) {
	return file_iotics_api_input_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ReceiveInputMessageResponse_Payload) GetInputId() *InputID {
	if x != nil {
		return x.InputId
	}
	return nil
}

func (x *ReceiveInputMessageResponse_Payload) GetMessage() *InputMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_iotics_api_input_proto protoreflect.FileDescriptor

var file_iotics_api_input_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49,
	0x0a, 0x07, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x77, 0x69,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x77, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0xbd, 0x01, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x3c, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x1a, 0x3a, 0x0a,
	0x09, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f,
	0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x44,
	0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x22, 0xc1, 0x01, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x41, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x1a, 0x38, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2d,
	0x0a, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x49, 0x44, 0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x22, 0xc1, 0x01,
	0x0a, 0x14, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x1a, 0x3a, 0x0a, 0x09, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x44, 0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49,
	0x64, 0x22, 0xfa, 0x02, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69,
	0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x43, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x69, 0x6f,
	0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a,
	0x6d, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69,
	0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x7e,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f, 0x74,
	0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x44, 0x52,
	0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x86,
	0x01, 0x0a, 0x13, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x0c, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x64, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xcd, 0x01, 0x0a, 0x1a,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f,
	0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x44, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x1a,
	0x3a, 0x0a, 0x09, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x07,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x49, 0x44, 0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x22, 0x85, 0x02, 0x0a, 0x1b,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69,
	0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x49, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x69, 0x6f,
	0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x6c, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x2d, 0x0a, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x49, 0x44, 0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x12,
	0x32, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xa1, 0x02, 0x0a, 0x08, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x50, 0x49,
	0x12, 0x50, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x1e, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x20, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x14, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x26, 0x2e, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x69, 0x6f, 0x74,
	0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x7e, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x69,
	0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x42, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x6f, 0x74, 0x69, 0x63, 0x2d, 0x4c, 0x61, 0x62, 0x73, 0x2f, 0x69,
	0x6f, 0x74, 0x69, 0x63, 0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x71, 0x61,
	0x70, 0x69, 0x2f, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x69, 0x6f,
	0x74, 0x69, 0x63, 0x73, 0x61, 0x70, 0x69, 0xa2, 0x02, 0x03, 0x49, 0x41, 0x58, 0xaa, 0x02, 0x0a,
	0x49, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x41, 0x70, 0x69, 0xca, 0x02, 0x0a, 0x49, 0x6f, 0x74,
	0x69, 0x63, 0x73, 0x5c, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iotics_api_input_proto_rawDescOnce sync.Once
	file_iotics_api_input_proto_rawDescData = file_iotics_api_input_proto_rawDesc
)

func file_iotics_api_input_proto_rawDescGZIP() []byte {
	file_iotics_api_input_proto_rawDescOnce.Do(func() {
		file_iotics_api_input_proto_rawDescData = protoimpl.X.CompressGZIP(file_iotics_api_input_proto_rawDescData)
	})
	return file_iotics_api_input_proto_rawDescData
}

var file_iotics_api_input_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_iotics_api_input_proto_goTypes = []interface{}{
	(*InputID)(nil),                              // 0: iotics.api.InputID
	(*DeleteInputRequest)(nil),                   // 1: iotics.api.DeleteInputRequest
	(*DeleteInputResponse)(nil),                  // 2: iotics.api.DeleteInputResponse
	(*DescribeInputRequest)(nil),                 // 3: iotics.api.DescribeInputRequest
	(*DescribeInputResponse)(nil),                // 4: iotics.api.DescribeInputResponse
	(*UpsertInputWithMeta)(nil),                  // 5: iotics.api.UpsertInputWithMeta
	(*InputMessage)(nil),                         // 6: iotics.api.InputMessage
	(*ReceiveInputMessageRequest)(nil),           // 7: iotics.api.ReceiveInputMessageRequest
	(*ReceiveInputMessageResponse)(nil),          // 8: iotics.api.ReceiveInputMessageResponse
	(*DeleteInputRequest_Arguments)(nil),         // 9: iotics.api.DeleteInputRequest.Arguments
	(*DeleteInputResponse_Payload)(nil),          // 10: iotics.api.DeleteInputResponse.Payload
	(*DescribeInputRequest_Arguments)(nil),       // 11: iotics.api.DescribeInputRequest.Arguments
	(*DescribeInputResponse_MetaResult)(nil),     // 12: iotics.api.DescribeInputResponse.MetaResult
	(*DescribeInputResponse_Payload)(nil),        // 13: iotics.api.DescribeInputResponse.Payload
	(*ReceiveInputMessageRequest_Arguments)(nil), // 14: iotics.api.ReceiveInputMessageRequest.Arguments
	(*ReceiveInputMessageResponse_Payload)(nil),  // 15: iotics.api.ReceiveInputMessageResponse.Payload
	(*Headers)(nil),                              // 16: iotics.api.Headers
	(*Value)(nil),                                // 17: iotics.api.Value
	(*Property)(nil),                             // 18: iotics.api.Property
	(*timestamppb.Timestamp)(nil),                // 19: google.protobuf.Timestamp
}
var file_iotics_api_input_proto_depIdxs = []int32{
	16, // 0: iotics.api.DeleteInputRequest.headers:type_name -> iotics.api.Headers
	9,  // 1: iotics.api.DeleteInputRequest.args:type_name -> iotics.api.DeleteInputRequest.Arguments
	16, // 2: iotics.api.DeleteInputResponse.headers:type_name -> iotics.api.Headers
	10, // 3: iotics.api.DeleteInputResponse.payload:type_name -> iotics.api.DeleteInputResponse.Payload
	16, // 4: iotics.api.DescribeInputRequest.headers:type_name -> iotics.api.Headers
	11, // 5: iotics.api.DescribeInputRequest.args:type_name -> iotics.api.DescribeInputRequest.Arguments
	16, // 6: iotics.api.DescribeInputResponse.headers:type_name -> iotics.api.Headers
	13, // 7: iotics.api.DescribeInputResponse.payload:type_name -> iotics.api.DescribeInputResponse.Payload
	17, // 8: iotics.api.UpsertInputWithMeta.values:type_name -> iotics.api.Value
	18, // 9: iotics.api.UpsertInputWithMeta.properties:type_name -> iotics.api.Property
	19, // 10: iotics.api.InputMessage.occurredAt:type_name -> google.protobuf.Timestamp
	16, // 11: iotics.api.ReceiveInputMessageRequest.headers:type_name -> iotics.api.Headers
	14, // 12: iotics.api.ReceiveInputMessageRequest.args:type_name -> iotics.api.ReceiveInputMessageRequest.Arguments
	16, // 13: iotics.api.ReceiveInputMessageResponse.headers:type_name -> iotics.api.Headers
	15, // 14: iotics.api.ReceiveInputMessageResponse.payload:type_name -> iotics.api.ReceiveInputMessageResponse.Payload
	0,  // 15: iotics.api.DeleteInputRequest.Arguments.inputId:type_name -> iotics.api.InputID
	0,  // 16: iotics.api.DeleteInputResponse.Payload.inputId:type_name -> iotics.api.InputID
	0,  // 17: iotics.api.DescribeInputRequest.Arguments.inputId:type_name -> iotics.api.InputID
	17, // 18: iotics.api.DescribeInputResponse.MetaResult.values:type_name -> iotics.api.Value
	18, // 19: iotics.api.DescribeInputResponse.MetaResult.properties:type_name -> iotics.api.Property
	0,  // 20: iotics.api.DescribeInputResponse.Payload.inputId:type_name -> iotics.api.InputID
	12, // 21: iotics.api.DescribeInputResponse.Payload.result:type_name -> iotics.api.DescribeInputResponse.MetaResult
	0,  // 22: iotics.api.ReceiveInputMessageRequest.Arguments.inputId:type_name -> iotics.api.InputID
	0,  // 23: iotics.api.ReceiveInputMessageResponse.Payload.inputId:type_name -> iotics.api.InputID
	6,  // 24: iotics.api.ReceiveInputMessageResponse.Payload.message:type_name -> iotics.api.InputMessage
	1,  // 25: iotics.api.InputAPI.DeleteInput:input_type -> iotics.api.DeleteInputRequest
	3,  // 26: iotics.api.InputAPI.DescribeInput:input_type -> iotics.api.DescribeInputRequest
	7,  // 27: iotics.api.InputAPI.ReceiveInputMessages:input_type -> iotics.api.ReceiveInputMessageRequest
	2,  // 28: iotics.api.InputAPI.DeleteInput:output_type -> iotics.api.DeleteInputResponse
	4,  // 29: iotics.api.InputAPI.DescribeInput:output_type -> iotics.api.DescribeInputResponse
	8,  // 30: iotics.api.InputAPI.ReceiveInputMessages:output_type -> iotics.api.ReceiveInputMessageResponse
	28, // [28:31] is the sub-list for method output_type
	25, // [25:28] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_iotics_api_input_proto_init() }
func file_iotics_api_input_proto_init() {
	if File_iotics_api_input_proto != nil {
		return
	}
	file_iotics_api_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_iotics_api_input_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeInputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeInputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertInputWithMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveInputMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveInputMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInputRequest_Arguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInputResponse_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeInputRequest_Arguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeInputResponse_MetaResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeInputResponse_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveInputMessageRequest_Arguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iotics_api_input_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveInputMessageResponse_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iotics_api_input_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iotics_api_input_proto_goTypes,
		DependencyIndexes: file_iotics_api_input_proto_depIdxs,
		MessageInfos:      file_iotics_api_input_proto_msgTypes,
	}.Build()
	File_iotics_api_input_proto = out.File
	file_iotics_api_input_proto_rawDesc = nil
	file_iotics_api_input_proto_goTypes = nil
	file_iotics_api_input_proto_depIdxs = nil
}
